#ifndef TEXTURES_H
#define TEXTURES_H

#include <d3d11.h>

#include "ILogger.h"

namespace testbed {
/**
 * \brief Sourced textures are textures that are loaded from files.
 */
struct SourcedTextureInfo {
	unsigned char *data;
	unsigned int width;
	unsigned int height;
	DXGI_FORMAT format;
};

/**
 * \brief Feature textures are textures that are generated by the engine.
 */
struct FeatureTextureInfo {
	unsigned int width;
	unsigned int height;
	DXGI_FORMAT format;
};

void InitializeTextureSystem(ILogger *newLogger);

void CreateFeatureTexture(const char *name, const FeatureTextureInfo &info);
// TODO: Add source texture creation

ID3D11RenderTargetView *GetTextureRTV(const char *name);
ID3D11ShaderResourceView *GetTextureSRV(const char *name);

}  // namespace testbed

#endif	// TEXTURES_H
